name: Triangle Conversion
on:
  push:
    branches: [ master ]

jobs:
  Units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/units

  Deploy:
    runs-on: ubuntu-latest
    needs: [Units]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          s3-bucket: ${{ secrets.S3_BUCKET }}
          cloudfront-id: ${{ secrets.CLOUDFRONT_ID }}
